driver:
  name: dokken
  chef_version: current
  privileged: true # because Docker and SystemD/Upstart
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  root_path: '/opt/verifier'
  sudo: false

platforms:
- name: centos-6
  driver:
    image: dokken/centos-6
    platform: rhel
    pid_one_command: /sbin/init

- name: centos-7
  driver:
    image: dokken/centos-7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd

- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd

- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd

- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd

# Use test suites defined in base .kitchen.yml
