---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: doc

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[sensu-go-chef::default]
    attributes:
