---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    chef_license: accept

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: centos-6
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[sensu_test::default]
    attributes:
